{
 "title": "CC Heartbeat",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Broker Connection Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "heartbeat_connection_latency_ms",
     "legendFormat": "{{cluster_id}} broker {{broker}}"
    }
   ]
  },
  {
   "title": "Produce / Consume Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "heartbeat_avg_produce_latency_ms",
     "legendFormat": "Produce {{cluster_id}}"
    },
    {
     "expr": "heartbeat_avg_consume_latency_ms",
     "legendFormat": "Consume {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Messages Produced & Consumed",
   "type": "timeseries",
   "description": "Rate of message production per minute",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(heartbeat_messages_produced[30s])",
     "legendFormat": "Produced"
    },
    {
     "expr": "rate(heartbeat_messages_consumed[30s])",
     "legendFormat": "Consumed"
    }
   ]
  },
  {
   "title": "Broker Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "heartbeat_broker_count" }
   ]
  },
  {
   "title": "Controller ID",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "heartbeat_controller" }
   ]
  }
 ]
}