apiVersion: 1
deleteDatasources:
  - name: cc_heartbeat
    orgId: 1

datasources:
- name: cc_heartbeat
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  isDefault: true
  # <map> fields that will be converted to json and stored in json_data
  jsonData:
     # <string> the typical scrape and evaluation interval configured in Prometheus, used to calculate '$__rate_interval'
     timeInterval: 15s
     tlsAuth: false
     tlsAuthWithCACert: false
  version: 1
  editable: true